targets:
  Pulse:
    type: application
    supportedDestinations: [macOS, iOS]
    sources:
      - path: Apps/Pulse
        excludes: ["app.yml", "Info.plist"]
    dependencies:
      - package: OracleKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.laris.oracle.pulse
        PRODUCT_NAME: Pulse
        INFOPLIST_KEY_CFBundleDisplayName: Pulse
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
    info:
      path: Apps/Pulse/Info.plist
      properties:
        CFBundleName: Pulse
        CFBundleDisplayName: Pulse
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        CFBundleDocumentTypes:
          - CFBundleTypeName: Anything for Pulse
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes: [public.item, public.content, public.folder, public.url, public.data]
