targets:
  Neo:
    type: application
    supportedDestinations: [macOS, iOS]
    sources:
      - path: Apps/Neo
        excludes: ["app.yml", "Info.plist"]
    dependencies:
      - package: OracleKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.laris.oracle.neo
        PRODUCT_NAME: Neo
        INFOPLIST_KEY_CFBundleDisplayName: Neo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
    info:
      path: Apps/Neo/Info.plist
      properties:
        CFBundleName: Neo
        CFBundleDisplayName: Neo
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        CFBundleDocumentTypes:
          - CFBundleTypeName: Anything for Neo
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes: [public.item, public.content, public.folder, public.url, public.data]
